const columns = [
  { name: "CASE ID", uid: "caseID", sortable: true },
  { name: "FIR NO#", uid: "firNo", sortable: true },
  { name: "DATE", uid: "date", sortable: true },
  { name: "POLICE STATION", uid: "policeStation" },
  { name: "ENTERED BY", uid: "enteredBy" },
  { name: "DEPARTMENT", uid: "department" },
  { name: "STATUS", uid: "status", sortable: true },
  { name: "ACTIONS", uid: "actions" },
];

const statusOptions = [
  { name: "Active", uid: "active" },
  { name: "Completed", uid: "completed" },
  { name: "Pending", uid: "pending" },
];

const reports = [
  {
    id: 1,
    caseID: 87452,
    firNo: 5623,
    date: "21-8-2024",
    department: "Police Forensic Department",
    status: "completed",
    policeStation: "Central",
    enteredBy: "Sarah Khan",
  },
  {
    id: 2,
    caseID: 39485,
    firNo: 7871,
    date: "19-8-2024",
    department: "Chemical Examination Department",
    status: "active",
    policeStation: "East",
    enteredBy: "John Doe",
  },
  {
    id: 3,
    caseID: 12365,
    firNo: 4589,
    date: "25-8-2024",
    department: "ICCBS DNA Department",
    status: "pending",
    policeStation: "West",
    enteredBy: "Ali Ahmed",
  },
  {
    id: 4,
    caseID: 65987,
    firNo: 5621,
    date: "18-8-2024",
    department: "Police Surgeon Office",
    status: "completed",
    policeStation: "North",
    enteredBy: "Emily Davis",
  },
  {
    id: 5,
    caseID: 90873,
    firNo: 9632,
    date: "20-8-2024",
    department: "ICCBS DNA Department",
    status: "active",
    policeStation: "Central",
    enteredBy: "Michael Brown",
  },
  {
    id: 6,
    caseID: 76543,
    firNo: 1478,
    date: "22-8-2024",
    department: "Chemical Examination Department",
    status: "pending",
    policeStation: "South",
    enteredBy: "Nadia Iqbal",
  },
  {
    id: 7,
    caseID: 28476,
    firNo: 2365,
    date: "23-8-2024",
    department: "Police Surgeon Office",
    status: "active",
    policeStation: "East",
    enteredBy: "James Smith",
  },
  {
    id: 8,
    caseID: 48732,
    firNo: 4872,
    date: "21-8-2024",
    department: "Police Forensic Department",
    status: "completed",
    policeStation: "West",
    enteredBy: "Laura Wilson",
  },
  {
    id: 9,
    caseID: 69583,
    firNo: 7845,
    date: "24-8-2024",
    department: "ICCBS DNA Department",
    status: "pending",
    policeStation: "North",
    enteredBy: "Daniel Green",
  },
  {
    id: 10,
    caseID: 37591,
    firNo: 9674,
    date: "25-8-2024",
    department: "Chemical Examination Department",
    status: "completed",
    policeStation: "Central",
    enteredBy: "Sophia Johnson",
  },
  {
    id: 11,
    caseID: 98234,
    firNo: 2384,
    date: "22-8-2024",
    department: "Police Forensic Department",
    status: "active",
    policeStation: "East",
    enteredBy: "Kevin Lee",
  },
  {
    id: 12,
    caseID: 74829,
    firNo: 5893,
    date: "23-8-2024",
    department: "Police Surgeon Office",
    status: "pending",
    policeStation: "West",
    enteredBy: "David Clark",
  },
  {
    id: 13,
    caseID: 56421,
    firNo: 6521,
    date: "21-8-2024",
    department: "Chemical Examination Department",
    status: "completed",
    policeStation: "North",
    enteredBy: "Olivia White",
  },
  {
    id: 14,
    caseID: 98374,
    firNo: 7893,
    date: "25-8-2024",
    department: "Police Surgeon Office",
    status: "active",
    policeStation: "South",
    enteredBy: "Henry Miller",
  },
  {
    id: 15,
    caseID: 28473,
    firNo: 1479,
    date: "19-8-2024",
    department: "Police Forensic Department",
    status: "pending",
    policeStation: "Central",
    enteredBy: "Eleanor Scott",
  },
  {
    id: 16,
    caseID: 49827,
    firNo: 5487,
    date: "22-8-2024",
    department: "ICCBS DNA Department",
    status: "completed",
    policeStation: "East",
    enteredBy: "Amir Ali",
  },
  {
    id: 17,
    caseID: 78125,
    firNo: 1236,
    date: "24-8-2024",
    department: "Chemical Examination Department",
    status: "active",
    policeStation: "West",
    enteredBy: "Fatima Khan",
  },
  {
    id: 18,
    caseID: 34985,
    firNo: 9765,
    date: "20-8-2024",
    department: "Police Surgeon Office",
    status: "pending",
    policeStation: "North",
    enteredBy: "Zain Raza",
  },
  {
    id: 19,
    caseID: 98721,
    firNo: 2145,
    date: "23-8-2024",
    department: "Police Forensic Department",
    status: "completed",
    policeStation: "Central",
    enteredBy: "Hassan Qureshi",
  },
  {
    id: 20,
    caseID: 65783,
    firNo: 4598,
    date: "25-8-2024",
    department: "ICCBS DNA Department",
    status: "active",
    policeStation: "South",
    enteredBy: "Ayesha Tariq",
  },
];

export { columns, reports, statusOptions };
